name: onnx-stan
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - onnx
  - numpy
  - pybind11
  - cmake
  - pystan
  - setuptools
  - protobuf
  - pip:
    - onnxruntime
