name: onnx-stan
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - onnx
  - numpy
  - pybind11
  - cmake
  - pystan
  - m2w64-toolchain  # This provides the GCC toolchain on Windows
  - setuptools
  - protobuf
  - pip:
    - onnxruntime
