name: onnx-stan
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - onnx
  - numpy
  - pybind11
  - cmake
  - pystan
  - setuptools
  - protobuf
  - pip:
    - onnxruntime
  - gxx_linux-64 # Linux
  - gcc_linux-64 # Linux
  - clang_osx-64 # MacOS
  - clangxx_osx-64 # MacOS
  - m2w64-toolchain  # Windows
